services:
  app:
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      context: .
      # Имя Docker-файла из которого будет собран образ
      dockerfile: Dockerfile
    # Команда, которая будет выполнена после старта сервиса
    command: make dev
    ports: # Проброс портов
      - "8080:8080"
    volumes:
      # Текущая директория пробрасывается в директорию /app внутри контейнера
      # Путь внутри контейнера (после двоеточия) обязательно должен быть абсолютным
      - "./app:/app"

  caddy:
    # Используем официальный образ Caddy. Рекомендуется указывать конкретную версию.
    image: caddy:2.7-alpine

    # Пробрасываем порты наружу. 80 для HTTP, 443 для HTTPS.
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # Для HTTP/3, опционально, но хорошая практика

    # Монтируем конфигурационный файл Caddyfile внутрь контейнера.
    # ./services/caddy/Caddyfile (на вашем компьютере) -> /etc/caddy/Caddyfile (внутри контейнера)
    volumes:
      - ./services/caddy:/etc/caddy

    # Устанавливаем зависимость от сервиса `app`.
    # Это гарантирует, что Caddy запустится только ПОСЛЕ того, как запустится `app`.
    depends_on:
      - app